title: Najeeb Ahmed Bhuiyan
logo: dp-sq.jpeg
description: B.Sc.Engg. in Mechatronics Engineering from RUET, currently working on Robotics, Edge-AI and related projects!
show_downloads: true
theme: jekyll-theme-minimal
