title: Najeeb Ahmed Bhuiyan
logo: dp.jpg
description: Undergraduate student studying Mechatronics Engineering at RUET, currently working on TinyML and related projects!
show_downloads: true
theme: jekyll-theme-minimal
