title: Najeeb Ahmed Bhuiyan
logo: dp-raaicon-sq.jpeg
description: Lecturer in CSE at Daffodil International University and Mechatronics Engineer specializing in Robotics and Edge-AI Research.
show_downloads: true
theme: jekyll-theme-minimal
